### ISSUE TITLE
Find a proper dataset

### ISSUE THREAD

**Issue by gdikov** [taimir/ImmersiveDriving#2]
* CamVid: http://mi.eng.cam.ac.uk/research/projects/VideoRec/CamVid/

**Comment by gdikov** [comment]
Login in Azure ML portal: https://studio.azureml.net/

**Comment by taimir** [comment]
What do you think: http://places.csail.mit.edu/

**Comment by uteschiehlen** [comment]
Google dataset: http://crcv.ucf.edu/data/GMCP_Geolocalization/

**Comment by gdikov** [comment]
pretrained model: https://github.com/metalbubble/places365

**Comment by taimir** [comment]
Preprocessing: https://github.com/BVLC/caffe/blob/master/matlab/demo/classification_demo.m
